# Stage 1: Build
FROM node:14.17.3-alpine AS build

ARG DORY_API_URL
ARG FIREBASE_API_KEY
ARG FIREBASE_APP_ID
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_LOCATION_ID
ARG FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_STORAGE_BUCKET
ARG MAPS_API_KEY
ARG OAUTH_CLIENT_ID_WEB
ARG OAUTH_CLIENT_ID
ARG DORY_SERVER_URL
ARG THIS_WEB_URL
ARG GINELECT_URL
ARG LIMIT_PHOTOS_FORUM
ARG LIMIT_PHOTOS_USER_SERVICES


WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

ENV DORY_API_REST=${DORY_API_URL}/api
ENV FIREBASE_API_KEY=${FIREBASE_API_KEY}
ENV FIREBASE_APP_ID=${FIREBASE_APP_ID}
ENV FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
ENV FIREBASE_LOCATION_ID=${FIREBASE_LOCATION_ID}
ENV FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
ENV FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
ENV FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
ENV MAPS_API_KEY=${MAPS_API_KEY}
ENV OAUTH_CLIENT_ID_WEB=${OAUTH_CLIENT_ID_WEB}
ENV OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
ENV DORY_SERVER_URL=${DORY_SERVER_URL}
ENV THIS_WEB_URL=${THIS_WEB_URL}
ENV GINELECT_URL=${GINELECT_URL}
ENV LIMIT_PHOTOS_FORUM=${LIMIT_PHOTOS_FORUM}
ENV LIMIT_PHOTOS_USER_SERVICES=${LIMIT_PHOTOS_USER_SERVICES}

RUN npm run build

# Stage 2
FROM nginx:1.17.1-alpine
COPY --from=build /usr/src/app/dist/web-app-dory /usr/share/nginx/html
COPY --from=build /usr/src/app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
